### ISSUE TITLE
Incorrect benchmark

### ISSUE THREAD

**Issue by Player3324** [Techcable/Event4J#1]
From what I can tell your benchmark code has no listeners for asmBus.

I did remotely related tests myself a while ago and reflection wasn't too bad compared to direct invocation if the Method instance is cached. Only method handles performed really poorly in some more complex scenarios, suggesting a higher dependency on successful constant folding.

**Comment by Techcable** [comment]
Reflection method objects _are_ cached. Reflection would be two or three orders of magnitude slower otherwise ;)
