### ISSUE TITLE
Benchmark: jvm flags, MethodHandle speed

### ISSUE THREAD

**Issue by Janmm14** [Techcable/Event4J#2]
According to some stackoverflow answers, MethodHandle performance relies on `-client` and `-server` partly. So it would be nice if you can create some benchmarks with different jvm flags.

http://stackoverflow.com/questions/15621434/methodhandle-perfomance
And the links given there.

**Comment by Techcable** [comment]
Server is default with linux, and no one cares about the client JVM.
